/* Generated by Yosys 0.66 (git sha1 86f2ddebce7e98ce7cacc27e8a5c14cb53b51b51, clang++ 21.1.8 -fPIC -O3) */

module counter(clock_i, reset_n_i, enable_i, counter_value_o);
  input clock_i;
  wire clock_i;
  input reset_n_i;
  wire reset_n_i;
  input enable_i;
  wire enable_i;
  output [7:0] counter_value_o;
  wire [7:0] counter_value_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  sg13cmos5l_inv_1 _37_ (
    .A(counter_value_o[3]),
    .Y(_08_)
  );
  sg13cmos5l_nand4_1 _38_ (
    .A(enable_i),
    .B(counter_value_o[2]),
    .C(counter_value_o[1]),
    .D(counter_value_o[0]),
    .Y(_09_)
  );
  sg13cmos5l_buf_4 _39_ (
    .A(_09_),
    .X(_10_)
  );
  sg13cmos5l_o21ai_1 _40_ (
    .A1(_08_),
    .A2(_10_),
    .B1(counter_value_o[4]),
    .Y(_11_)
  );
  sg13cmos5l_or3_1 _41_ (
    .A(_08_),
    .B(counter_value_o[4]),
    .C(_10_),
    .X(_12_)
  );
  sg13cmos5l_inv_1 _42_ (
    .A(reset_n_i),
    .Y(_13_)
  );
  sg13cmos5l_a21oi_1 _43_ (
    .A1(_11_),
    .A2(_12_),
    .B1(_13_),
    .Y(_00_)
  );
  sg13cmos5l_nand2_1 _44_ (
    .A(counter_value_o[3]),
    .B(counter_value_o[4]),
    .Y(_14_)
  );
  sg13cmos5l_o21ai_1 _45_ (
    .A1(_10_),
    .A2(_14_),
    .B1(counter_value_o[5]),
    .Y(_15_)
  );
  sg13cmos5l_or3_1 _46_ (
    .A(counter_value_o[5]),
    .B(_10_),
    .C(_14_),
    .X(_16_)
  );
  sg13cmos5l_a21oi_1 _47_ (
    .A1(_15_),
    .A2(_16_),
    .B1(_13_),
    .Y(_01_)
  );
  sg13cmos5l_nand3_1 _48_ (
    .A(counter_value_o[3]),
    .B(counter_value_o[5]),
    .C(counter_value_o[4]),
    .Y(_17_)
  );
  sg13cmos5l_o21ai_1 _49_ (
    .A1(_10_),
    .A2(_17_),
    .B1(counter_value_o[6]),
    .Y(_18_)
  );
  sg13cmos5l_or3_1 _50_ (
    .A(counter_value_o[6]),
    .B(_10_),
    .C(_17_),
    .X(_19_)
  );
  sg13cmos5l_a21oi_1 _51_ (
    .A1(_18_),
    .A2(_19_),
    .B1(_13_),
    .Y(_02_)
  );
  sg13cmos5l_nand4_1 _52_ (
    .A(counter_value_o[3]),
    .B(counter_value_o[6]),
    .C(counter_value_o[5]),
    .D(counter_value_o[4]),
    .Y(_20_)
  );
  sg13cmos5l_o21ai_1 _53_ (
    .A1(_10_),
    .A2(_20_),
    .B1(counter_value_o[7]),
    .Y(_21_)
  );
  sg13cmos5l_or3_1 _54_ (
    .A(counter_value_o[7]),
    .B(_10_),
    .C(_20_),
    .X(_22_)
  );
  sg13cmos5l_a21oi_1 _55_ (
    .A1(_21_),
    .A2(_22_),
    .B1(_13_),
    .Y(_03_)
  );
  sg13cmos5l_xor2_1 _56_ (
    .A(enable_i),
    .B(counter_value_o[0]),
    .X(_23_)
  );
  sg13cmos5l_and2_1 _57_ (
    .A(reset_n_i),
    .B(_23_),
    .X(_04_)
  );
  sg13cmos5l_nand2_1 _58_ (
    .A(enable_i),
    .B(counter_value_o[0]),
    .Y(_24_)
  );
  sg13cmos5l_xnor2_1 _59_ (
    .A(counter_value_o[1]),
    .B(_24_),
    .Y(_25_)
  );
  sg13cmos5l_and2_1 _60_ (
    .A(reset_n_i),
    .B(_25_),
    .X(_05_)
  );
  sg13cmos5l_nand3_1 _61_ (
    .A(enable_i),
    .B(counter_value_o[1]),
    .C(counter_value_o[0]),
    .Y(_26_)
  );
  sg13cmos5l_xnor2_1 _62_ (
    .A(counter_value_o[2]),
    .B(_26_),
    .Y(_27_)
  );
  sg13cmos5l_and2_1 _63_ (
    .A(reset_n_i),
    .B(_27_),
    .X(_06_)
  );
  sg13cmos5l_xnor2_1 _64_ (
    .A(counter_value_o[3]),
    .B(_10_),
    .Y(_28_)
  );
  sg13cmos5l_and2_1 _65_ (
    .A(reset_n_i),
    .B(_28_),
    .X(_07_)
  );
  sg13cmos5l_dfrbpq_1 _66_ (
    .CLK(clock_i),
    .D(_02_),
    .Q(counter_value_o[6]),
    .RESET_B(_30_)
  );
  sg13cmos5l_dfrbpq_1 _67_ (
    .CLK(clock_i),
    .D(_03_),
    .Q(counter_value_o[7]),
    .RESET_B(_36_)
  );
  sg13cmos5l_dfrbpq_1 _68_ (
    .CLK(clock_i),
    .D(_04_),
    .Q(counter_value_o[0]),
    .RESET_B(_34_)
  );
  sg13cmos5l_dfrbpq_1 _69_ (
    .CLK(clock_i),
    .D(_05_),
    .Q(counter_value_o[1]),
    .RESET_B(_31_)
  );
  sg13cmos5l_dfrbpq_1 _70_ (
    .CLK(clock_i),
    .D(_06_),
    .Q(counter_value_o[2]),
    .RESET_B(_35_)
  );
  sg13cmos5l_dfrbpq_1 _71_ (
    .CLK(clock_i),
    .D(_07_),
    .Q(counter_value_o[3]),
    .RESET_B(_29_)
  );
  sg13cmos5l_dfrbpq_1 _72_ (
    .CLK(clock_i),
    .D(_00_),
    .Q(counter_value_o[4]),
    .RESET_B(_33_)
  );
  sg13cmos5l_dfrbpq_1 _73_ (
    .CLK(clock_i),
    .D(_01_),
    .Q(counter_value_o[5]),
    .RESET_B(_32_)
  );
  sg13cmos5l_tiehi _74_ (
    .L_HI(_29_)
  );
  sg13cmos5l_tiehi _75_ (
    .L_HI(_30_)
  );
  sg13cmos5l_tiehi _76_ (
    .L_HI(_31_)
  );
  sg13cmos5l_tiehi _77_ (
    .L_HI(_32_)
  );
  sg13cmos5l_tiehi _78_ (
    .L_HI(_33_)
  );
  sg13cmos5l_tiehi _79_ (
    .L_HI(_34_)
  );
  sg13cmos5l_tiehi _80_ (
    .L_HI(_35_)
  );
  sg13cmos5l_tiehi _81_ (
    .L_HI(_36_)
  );
endmodule
