// Auto-generated by LibreLane
module heichips26_loopcache_rv(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input[15:0] ui_in,
  output[15:0] uo_out,
  input[15:0] uio_in,
  output[15:0] uio_out,
  output[15:0] uio_oe,
  input ena,
  input rst_n
);
endmodule
