// Auto-generated by LibreLane
module counter(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clock_i,
  input reset_n_i,
  input enable_i,
  output[7:0] counter_value_o
);
endmodule
